name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Deploy AWS Infrastructure
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: "1.8.1"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: ${{ github.run_id }}

      - name: Initialize OpenTofu
        run: tofu init

      - name: Validate configuration
        run: tofu validate

      - name: Plan infrastructure changes
        run: tofu plan -out=tfplan
        env:
          TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
          TF_VAR_github_org: ${{ vars.GITHUB_ORG }}
          TF_VAR_github_repo: ${{ vars.GITHUB_REPO }}

      - name: Apply infrastructure changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: tofu apply -auto-approve tfplan

      - name: Upload plan for PR
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan
          retention-days: 5

      - name: Comment plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            
            try {
              const planOutput = execSync('cd terraform && tofu show -no-color tfplan', { encoding: 'utf8' });
              const truncatedPlan = planOutput.length > 65000 ? 
                planOutput.substring(0, 65000) + '\n...\n*Plan output truncated*' : 
                planOutput;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## Infrastructure Plan\n\`\`\`\n${truncatedPlan}\n\`\`\``
              });
            } catch (error) {
              console.error('Error generating plan comment:', error);
            }
