name: PR Preview

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - '.github/workflows/infrastructure.yml'
      - '*.md'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  preview:
    name: Build PR Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build
        env:
          PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.PUBLIC_MAPBOX_ACCESS_TOKEN }}
          PUBLIC_API_BASE_URL: ${{ vars.PUBLIC_API_BASE_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-pr-preview
          aws-region: us-west-2

      - name: Deploy PR preview to S3
        run: |
          PR_PREFIX="pr-${{ github.event.pull_request.number }}"
          aws s3 sync build/ s3://${{ vars.S3_BUCKET_NAME }}/$PR_PREFIX/ \
            --delete \
            --cache-control "public, max-age=300"

      - name: Create CloudFront invalidation for preview
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/pr-${{ github.event.pull_request.number }}/*"

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const previewUrl = `https://${{ vars.DOMAIN_NAME }}/pr-${prNumber}/`;
            
            // Find existing preview comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            const existingComment = comments.find(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes('## 🚀 PR Preview')
            );
            
            const commentBody = `## 🚀 PR Preview
            
            Your changes have been deployed to a preview environment:
            
            🔗 **Preview URL:** ${previewUrl}
            
            This preview will be automatically updated when you push new commits to this PR.
            
            ---
            *Preview deployed from commit: ${context.sha.substring(0, 7)}*`;
            
            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
            }

  cleanup:
    name: Cleanup PR Preview
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-cleanup
          aws-region: us-west-2

      - name: Remove PR preview from S3
        run: |
          aws s3 rm s3://${{ vars.S3_BUCKET_NAME }}/pr-${{ github.event.pull_request.number }}/ --recursive

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/pr-${{ github.event.pull_request.number }}/*"